name: Test Apps

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  BUNDLE_GEMFILE: ${{ github.workspace }}/example/Gemfile

jobs:
  build-testapp-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup
        uses: ./.github/actions/setup

      - name: Prepare Android
        uses: ./.github/actions/prepare-android

      - name: Build example for Android
        run: |
          mkdir -p example/android/app/src/main/assets
          yarn run build:android

  build-testapp-newarch-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup
        uses: ./.github/actions/setup

      - name: Prepare Android
        uses: ./.github/actions/prepare-android

      - name: Build example for Android (new arch)
        run: |
          mkdir -p example/android/app/src/main/assets
          ORG_GRADLE_PROJECT_newArchEnabled=true yarn run build:android

  build-testapp-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup
        uses: ./.github/actions/setup

      - name: Prepare iOS
        uses: ./.github/actions/prepare-ios

      - name: Install example cocoapods
        run: |
          (cd example/ios;bundle exec pod install)

      - name: Build example for iOS
        run: |
          yarn run build:ios

  build-testapp-newarch-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup
        uses: ./.github/actions/setup

      - name: Prepare iOS
        uses: ./.github/actions/prepare-ios
        with:
          cache-suffix: '-newarch'

      - name: Install example cocoapods (new arch)
        run: |
          (cd example/ios;rm -f Podfile.lock;RCT_NEW_ARCH_ENABLED=1 bundle exec pod install)

      - name: Build example for iOS (new arch)
        run: |
          yarn run build:ios
